### ISSUE TITLE
Cohen, Michal: TODOs

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/IntelliJ-Spartanizer#11]
_From @michalcohen on October 28, 2016 15:10_

- [x]  Use a picture, photo or distinct avatar.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (not) in search for a job.

_Copied from original issue: SpartanRefactoring/Spartanizer#564_

**Comment by zvili** [comment]
_From @michalcohen on October 28, 2016 15:49_

@YossiGil: Done.

**Comment by zvili** [comment]
_From @AnnaBel7 on October 28, 2016 15:53_

Wow! Amazing!
check out my karma page #565

**Comment by zvili** [comment]
_From @yossigil on October 29, 2016 2:16_

Add a "quality assurance" and "teaching" labels to this issue. Add a deadline (which?). .
 erase much of the junk you copied from the tutorial. Good luck.

**Comment by zvili** [comment]
_From @AdiOmari on October 29, 2016 16:58_

Profile and nick-name are good 👍 . Edit the issue to remove junk (duplicate content - last todo, and examples), keep only the todos . 
Assign yourself if you haven't done so yet (you may need to be invited to the project to do so, you will be invited once you do assignment 0).

**Comment by zvili** [comment]
_From @yossigil on November 18, 2016 8:22_

:+1:

**Comment by michalcohen** [comment]
Presenting the results of sprint 1:
* Seperated the Spartanizer logic part from the plugin in #5 In order to complete #29
* Expanding the POC to work with actual tips: #7 and continues in #29 
* Wrote short Wiki page on other plugins that can inspire us while writing our #15 
* Implemented an addon to the Intellij IDEA (as part of #7) #17 
* Searched for some useful plugin to use during development #18
