### ISSUE TITLE
Make sure that Version 0.4 runs successfully on your computer

### ISSUE THREAD

**Issue by orenafek** [TechnionYP5777/IntelliJ-Spartanizer#119]
Download the latest stable version (0.4) from the JetBrains Repository and make sure it runs on your
**IntelliJ IDEA Community Edition 2016.3**

Successful run should enable the activation of (at least) those two tippers :

-  Rename single parameter to ¢ 
``` java 
  void foo(int x) -> void foo(int ¢)
```

 -  Remove Redundant curly braces ( **LEONIDAS** )
``` java 
  if (false) { System.out.println(""); }  ->  if (false) System.out.println(""); 
```

Mark yourself and close this issue upon the last mark :

- [x] @amirsagiv83 

- [x] @AnnaBel7 

- [x] @michalcohen 

- [x] @RoeiRaz 

- [x] @RoeyMaor 

- [x] @SharonKL 
 
- [x] Me

**Comment by AnnaBel7** [comment]
The Leonidas tip doesn't work as it should, instead of getting a tip about the redundant curly braces I get this tip:

![image](https://cloud.githubusercontent.com/assets/22842727/24246417/e13da046-0fcf-11e7-8cdd-5c3ee0cf9721.png)

I also get this tip on almost the whole project, probably there is something wrong with this tip's canTip method.

**Comment by amirsagiv83** [comment]
As Anna mentioned above, the plugin works but it offers weird tips almost everywhere, and not just the one mentioned in the comment above.

**Comment by michalcohen** [comment]
I opened issue on this bug and working on it #120

**Comment by michalcohen** [comment]
you can now republish the corrected version @orenafek
