### ISSUE TITLE
Import the AST jar into IntelliJ

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#16]
As done by @amirsagiv83 and import as many classes from the spartanizer you can, that apply to AST.

**Comment by amirsagiv83** [comment]
Anna, in order to import the org.eclipse.jdt.core.dom library, find the library where you downloaded the Spartanizer repo into. now, from the IntelliJ, press Ctrl+Alt+Shift+s, now in the "modules" section, choose the plugin project you work on. On the right side, press the green '+' sign-> jars and directories-> choose the jar file you wish.
Now you can import in your code and use it 😃

**Comment by amirsagiv83** [comment]
After discussing this issue in today's meeting, We decided to close this issue and open others more specific instead.
