### ISSUE TITLE
IntelliJ Plugin Tutorial

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/IntelliJ-Spartanizer#4]

**Comment by yossigil** [comment]
Who is assigned? What's the milestone? Do we need to create one?

**Comment by yossigil** [comment]
Who is assigned? What's the milestone? Do we need to create one? @michalcohen!!!

**Comment by michalcohen** [comment]
Roey was initially assigned, but this issue will be postponed as we talked.

**Comment by yossigil** [comment]
then place it "on hold"

**Comment by RoeyMaor** [comment]
**This is the first part of the tutorial, and the idea is to get you to a state where you can compile and run the current code in this repo == set up your plugin development environment. Hopefully this will help team members who had some trouble. The implementation of the plugin will be discussed in part 2.**

-Download IntellliJ community edition 2016.2.x (you should totally have this already, seriously :-0 )

-Download and install the latest JDK (1.8.X) fit for your system form here:
http://www.oracle.com/technetwork/java/javase/downloads/index.html

-open the project, wait for intellij to finish all background loading.

Go to file-> project structure, and under Project SDK hit new->intellij platform plugin SDK:

 
![image](https://cloud.githubusercontent.com/assets/16507852/20651386/44ce8abe-b4ed-11e6-819e-d8d87251f7d6.png)

In the opened window select the installation folder of your intelliJ, hit ok:
![image](https://cloud.githubusercontent.com/assets/16507852/20651388/4d95ba64-b4ed-11e6-817a-4b9db7c841d4.png)

 
-when prompted to choose a JDK, choose the one you have just installed :
![image](https://cloud.githubusercontent.com/assets/16507852/20651389/511a2d28-b4ed-11e6-8852-93df1c35abcd.png)

 
-set your project’s SDK as the newly created sdk:
![image](https://cloud.githubusercontent.com/assets/16507852/20651391/551868e0-b4ed-11e6-9a38-1d25280fb625.png)
 
-also make sure your project language level is 8 (in the same window).

-clone the source code of intelliJ community edition to your machine, using the following git command:
 
![image](https://cloud.githubusercontent.com/assets/16507852/20651393/5af45512-b4ed-11e6-8aa5-4905ee48a9a8.png)

**--depth 1 is super important! You don’t want to be spending two days cloning!**
Cloning the source code is needed in order to use the IntelliJ libraries such as PSI.

-still under the project structure window, choose SDKs, select the newly created SDK, hit the sourcepath tab, and click the + to add sources to the project:
 
![image](https://cloud.githubusercontent.com/assets/16507852/20651399/681d9744-b4ed-11e6-8449-25174fe83c06.png)

Select the folder where you cloned the intelliJ community source code，and choose all of the files:
 
![image](https://cloud.githubusercontent.com/assets/16507852/20651400/6b2e366e-b4ed-11e6-9198-aa6766dad530.png)

Hit apply and ok.

-again, in the project structure window, choose modules, choose the intellij-spartanizer project, go to the dependencies tab, and make sure the default module sdk is the one we have created:
 
![image](https://cloud.githubusercontent.com/assets/16507852/20651402/72dfe09c-b4ed-11e6-949d-fe3d14662045.png)


All done! You should be able to run the project! When running an intellij plugin project, the result is the spawning of another intellij, containing the plugin!

**Comment by yossigil** [comment]
:100:

**Comment by RoeyMaor** [comment]
Since all of the group members have worked with and are familiarized with the POC code, then as i agreed with amir there is no need for part 2 of this tutorial.
closed.
