### ISSUE TITLE
Afek, Oren: TODOs.

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/IntelliJ-Spartanizer#8]
_From @orenafek on October 30, 2016 15:12_

- [x]  Use a picture, photo or distinct avatar. Don''t use an automatic icon.
- [x]  Make sure you present yourself by a readable **nick**.
- [x]  Describe yourself in the bio page.
- [x]  State that you are (**not**) in search for a job.

_Copied from original issue: SpartanRefactoring/Spartanizer#624_

**Comment by zvili** [comment]
_From @orenafek on October 30, 2016 15:15_

@orimarco  Done.

**Comment by zvili** [comment]
_From @RonGatenio on October 30, 2016 15:51_

Nice page Oren! Good job 👍 😃

**Comment by zvili** [comment]
_From @inbalzukerman on October 31, 2016 13:27_

Pretty Karma page 😄 😘 
(Or not?)

Check mine - #684

**Comment by zvili** [comment]
_From @yossigil on November 18, 2016 8:20_

:+1:

**Comment by orenafek** [comment]
**Issues iv'e worked on or contributed to during this sprint:**
#5 - Although this issue was marked _irrelevant_ after we have decided to not implement it in advance,
       In order to complete #29, (The two-tipper spartan plugin) @michalcohen and I have written a whole set 
       of aux methods.

#6 - same as above.
#7 - moved to #29.
#15 - Have begun the research, and found some other nice statically analyzing plugins for IntelliJ, and    
         finally dropped my research to work on the POC.
#17 - Done, with a great help of the research of @RoeiRaz 
#18 - Found PSIView, the equivalence to ASTView, presented to me by @orimarco 
#24 - my question.
#29 - together with @michalcohen, an actual working mini-spartanizer plugin (with two **raw PSI** tippers) was released. This was a great effort that took most of our efforts and working hours.
